name: GitHub Actions Demo
on: [ push, pull_request ]

jobs:
    test:
        name: "Run tests"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout sources
                uses: actions/checkout@v2
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    java-version: '11'
                    distribution: 'temurin'
                    cache: maven
            -   name: Test with Maven
                run: mvn -B test